# -*- coding: UTF-8 -*-

# common intents
def common():
	return {
		"yes"					: [{"stem":"yes"},{"stem":"igen"},{"stem":"aha"},{"stem":"ja","affix":["ja","h"]},{"stem":"ok","affix":["é","s","és","sa","ay"],"exc":[{"stem":"nem"}]},{"stem":"jól","inc":[{"stem":"ért","wordclass":"verb"}],"exc":[{"stem":"nem"}]},{"stem":"rendben","exc":[{"stem":"nincs"}]}],
		"no"					: [{"stem":"no","max_words":3},{"stem":"nem","exc":[{"stem":"megy"},{"stem":"baj"},{"stem":"tud","wordclass":"verb"},{"stem":"ért","wordclass":"verb"}]},{"stem":"ne","exc":[{"stem":"haragudj","affix":["on"]}]},{"stem":"soha"},{"stem":"mégse","affix":["m"]},{"stem":"ros+z\s(v[aá]lasz|vic+|megold[aá]s)","wordclass":"regex"},{"stem":"nincs rendben"}],
		"hi" 					: [{"stem":"ha?i+","wordclass":"regex"},{"stem":"s+z+i+[aoó](ka|sztok)?","wordclass":"regex"},{"stem":"helló","affix":["ka"]},{"stem":"szer?[bv][au]sz(tok)?","wordclass":"regex"},{"stem":"hali","affix":["hó"]},{"stem":"(sz[eé]p|j[oó])\s?(reg+el|nap|est[eé])(o?t|[eéuü]nk)","wordclass":"regex"},{"stem":"[uü]dv([oö]z[oö]?l+(e[kt])?([eoö]m)?)?","wordclass":"regex"},{"stem":"örvendek"}],
		"bye" 				: [{"stem":"bye"},{"stem":"viszlát"},{"stem":"viszont látásra"},{"stem":"jó éj","affix":["t","szakát"]},{"stem":"jóccakát"},{"stem":"mennem kell"},{"stem":"csumi"},{"stem":"cs[aáoöő]+[oó]*(v[aá]z?)?","wordclass":"regex"},{"stem":"puszi"}],
		"thx"					: [{"stem":"(ezer\s?)?(k[oö]s+z|k[oösz][oösz][oösz])(i(ke)?|ke|[oö]n[oö]m|[oö]nj[uü]k|[eoö]net(em)?|csi|ent+y[uüű])?(\s?sz[eé]pen)?","wordclass":"regex"},{"stem":"[ht][ht]x","wordclass":"regex"},{"stem":"t(ha|h?e)nks?\s?(you)?","wordclass":"regex"},{"stem":"danke"}],
		"pls"					: [{"stem":"p+l+[iíea]*[zs]+e*","wordclass":"regex"},{"stem":"l[eé]+[cgyt]+[sz]*[ií]+(ves|keh?)?","wordclass":"regex"},{"stem":"l[eé](sz(el)?|gy(en)?|n+[eé]l).*?(kedves|sz[ií](ves)?)","wordclass":"regex"},{"stem":"szeretn[eé](k|m)","wordclass":"regex","exc":[{"stem":"(meg)?bocs(i(ka)?|[aá](nat([aá][eé]rt)?|nat[aáo]t?|s+|s+on|j?t(ana)?))?","wordclass":"regex"},{"stem":"elnézés","wordclass":"noun","match_stem":False}]},{"stem":"(meg)?k[eé]r(het)?((n[eéi])?l?e?[km]?)","wordclass":"regex","exc":[{"stem":"(meg)?bocs(i(ka)?|[aá](nat([aá][eé]rt)?|nat[aáo]t?|s+|s+on|j?t(ana)?))?","wordclass":"regex"},{"stem":"elnézés","wordclass":"noun","match_stem":False}]},{"stem":"szeretn[eé]([km]|lek)","wordclass":"regex","exc":[{"stem":"(meg)?bocs(i(ka)?|[aá](nat([aá][eé]rt)?|nat[aáo]t?|s+|s+on|j?t(ana)?))?","wordclass":"regex"},{"stem":"elnézés","wordclass":"noun","match_stem":False}]}],
		"welks"				: [{"stem":"nincs mit"},{"stem":"(nagyon\s?)?(is\s)?sz[ií]ves(en|\s?[oö]r[oö]mest)","wordclass":"regex"},{"stem":"ugyan\,?\shag[gy]\w{1,3}","wordclass":"regex"},{"stem":"hag[gy]\w{1,3}\scsak","wordclass":"regex"},{"stem":"sz[aá]momra.+?([oö]r[oö]m|megtiszteltet[eé]s)","wordclass":"regex"}],
		"sorry"				: [{"stem":"(meg)?bocs(i(ka)?|esz|[aá](nat([aá][eé]rt)?|nat[aáo]t?|s+|s+on|j?t(ana)?))?","wordclass":"regex"},{"stem":"elnézés","wordclass":"noun","match_stem":False},{"stem":"sajn[aá]l(om|juk)","wordclass":"regex"},{"stem":"s+z*o+r+[iy]+","wordclass":"regex"}],
		"lol"					: [{"stem":"(h[aei]){2,}h?","wordclass":"regex"},{"stem":"o?(lol)+o?","wordclass":"regex"},{"stem":"[\:\;]\-*[dp\)9]+","wordclass":"regex","boundary":False},{"stem":"[\(8]+\-*[:;]","wordclass":"regex","boundary":False},{"stem":"rot?fl","wordclass":"regex"},{"stem":"vicces","exc":[{"stem":"nem"}]},{"stem":"nevet(tem|ek|[uü]nk)","wordclass":"regex","exc":[{"stem":"nem"}]}],
		"nvm"				: [{"stem":"felejts[ed]n?\sel","wordclass":"regex"},{"stem":"mindegy","exc":[{"stem":"hogy"},{"stem":"nem"}]},{"stem":"nem fontos"},{"stem":"hagy(jad?|d)","wordclass":"regex","inc":[{"stem":"jól","affix":["van"]},{"stem":"á"},{"stem":"mindegy"},{"stem":"inkább"}]},{"stem":"ne\s(is\s)?(foglalkoz+(on|[aá]l)?|t[oö]r[oöő]dj([oö]n|[eé]l)?)\s(vel(e|[uü]k)|[ae][vz]+[ae]l)","wordclass":"regex"},{"stem":"hagy\w+\sfigyelmen\sk[ií]v[uü]l","wordclass":"regex","exc":[{"stem":"ne"}]}],
		"help"				: [{"stem":"segít","wordclass":"verb"},{"stem":"segítség","wordclass":"noun"},{"stem":"help","wordclass":"verb","prefix":[]}],
		"again"				: [{"stem":"[uú]j(ra|b[oó]l)|(meg)?ism[eé]t(l[eé]s|el(je|ni)?d?)?|m[eé]g\s?egyszer|megint?","wordclass":"regex"}],
		"command"		: [{"stem":"(csin[aá]l(jad?|d)|(keres|mutas|mond)[aedjos]+n?|n[eé]z[nz]?[eé]?[dl]|akaro[km]|utas[ií]t\w{1,})","wordclass":"regex"},{"stem":"haj[cts]+(a|[aá]?[ld])\sv[eé]gre","wordclass":"regex"}],
		"question"			: [{"stem":"(\?+$)|(\?+\s\w+)","wordclass":"regex"},{"stem":"([^,][^,\S+]hogy|^hogy)(an)?","wordclass":"regex"},{"stem":"hol"},{"stem":"honnan"},{"stem":"hová"},{"stem":"hány","affix":["an","at","ból"]},{"stem":"mettől"},{"stem":"meddig"},{"stem":"merre"},{"stem":"mennyi","affix":["en","re"]},{"stem":"mi","affix":["t","k","ket","kor","korra","lyen","lyenek","nek","től","kortól","korra","ből","hez","re","vel"]},{"stem":"ki(k?(e?t|nek|[bt][oöő]l|hez|re|[kv]el)|\saz?)","wordclass":"regex"}],
		"conditional"		: [{"stem":"volna"},{"stem":"lenne"},{"stem":"\w+h[ae]t\w+","wordclass":"regex"}],
		"profanity"			: [{"stem":"(fel|le|meg|r[aá]|ki|be|oda|[oö]s+ze|bele|hoz+[aá])?bas*z+d?\s?(at)?(hat)?(us|a[dk]?|n?[aá][kl]|[aá]?t[aáo][lkm]?|ot+|ni|n[aá]n?[dlkm]?|va|meg)?","wordclass":"regex","exc":[{"stem":"megye"}]},{"stem":"fasz","prefix":["ló","agy"],"wordclass":"noun"},{"stem":"fasza","wordclass":"adjective"},{"stem":"geci","wordclass":"noun"},{"stem":"kurva","affix":["élet","anya","anyja","annya"],"wordclass":"noun"},{"stem":"hülye","wordclass":"adjective"},{"stem":"pi(n|cs)[aá][dk]?(a?t|nak|ban?|[bt][oó]l|[eé]rt)?","wordclass":"regex"},{"stem":"((bekap(ja?|hato?|n[aái])?d?)|(kap.*?be))","wordclass":"regex"},{"stem":"(le)?szop(sz|ol|[jn][aá][dl]|hat(sz|n[aá]l|o[dl]))(\s?(le|ki))?","wordclass":"regex"},{"stem":"(geci|kurva)?(fos|szar)\w{0,3}","wordclass":"regex"}],
		"welldone"			: [{"stem":"fasza"},{"stem":"nagyszerű"},{"stem":"remek","max_words":5},{"stem":"jó","prefix":["kurva"],"exc":[{"stem":"nincs"},{"stem":"nem"},{"stem":"éjt"},{"stem":"reggelt"},{"stem":"napot"},{"stem":"estét"},{"stem":"éjszakát"}]},{"stem":"j[oó]l\s?van","wordclass":"regex"},{"stem":"király"},{"stem":"ügyes"},{"stem":"(sz[eé]p\s(volt|munka))|(ez\s(lesz\s)?az)|(sz?uper)|zs[ií]r","wordclass":"regex"},{"stem":"👍","wordclass":"emoji"},{"stem":"\(Y\)","wordclass":"regex","boundary":False},{"stem":"profi vagy"},{"stem":"fant[aoö](rp|sz?t)i[ck](us)?(an)?","wordclass":"regex"},{"stem":"szeretem","inc":[{"stem":"amikor"},{"stem":"ahogy"}],"exc":[{"stem":"nem"}]}],
		"dontknow"		: [{"stem":"fogalmam sincs","affix":["en"]},{"stem":"(m[eé]g)?[ns]em?\stud(hat)?o\w+","wordclass":"regex"},{"stem":"hon+an.+?tud(jam|(hat)?n[aá]m)","wordclass":"regex"}],
		"dontunderstand": [{"stem":"(m[eé]g)?[ns]em?\s([eé]rte(t+e)?[lm](ek)?|v[aá]gom|hal+[ao](t+a)?[km])","wordclass":"regex"},{"stem":"(mit|hogy(an))\s([eé]rte(t+[eé])?|mond(t[aá])?o?)(sz|d|l)","wordclass":"regex"},{"stem":"meg\s?ism[eé]tel(het)?n\w+","wordclass":"regex"}],
	}

# menu commands
def commands():
	return {
		"ok"					: [{"stem":"ye","affix":["s","ah","p"]},{"stem":"igen"},{"stem":"aha"},{"stem":"ja","affix":["ja","h"]},{"stem":"ok","affix":["é","s","és","sa","ay","ézd","ézza"],"exc":[{"stem":"nem"}]},{"stem":"úgy","exc":[{"stem":"nem"}]},{"stem":"így","exc":[{"stem":"((m[eé]g)?[ns]em*i?|baj)","wordclass":"regex"}]},{"stem":"jó","wordclass":"adjective","max_words":4,"exc":[{"stem":"((m[eé]g)?[ns]em*i?|baj)","wordclass":"regex"},{"stem":"(nap\w+|reg+elt|est[eé]t)","wordclass":"regex"}]}],
		"cancel"				: [{"stem":"^([ae]z\s)?(\w+\s)?(nem?|no(pe|ne)?)(\s\w+)?(\s\w+)?$","boundary":False,"exc":[{"stem":"jó"},{"stem":"tud","wordclass":"verb"},{"stem":"sikerül","affix":["t"]},{"stem":"haragudj","affix":["on"]},{"stem":"tud","wordclass":"verb"}],"wordclass":"regex"},{"stem":"cancel"},{"stem":"mégse","affix":["m"],"max_words":4},{"stem":"elvetés"},{"stem":"ves[ds]e?\sel","wordclass":"regex"}],
		"next"				: [{"stem":"next"},{"stem":"tovább","max_words":5,"exc":[{"stem":"((m[eé]g)?[ns]em*i?|baj)","wordclass":"regex"}]},{"stem":"előre","max_words":5,"exc":[{"stem":"((m[eé]g)?[ns]em*i?|baj)","wordclass":"regex"}]},{"stem":"még","max_words":4,"exc":[{"stem":"((m[eé]g)?[ns]em*i?|baj)","wordclass":"regex"},{"stem":"egy"},{"stem":"1"},{"stem":"hang\w*","wordclass":"regex"}]},{"stem":"more"},{"stem":"continue"},{"stem":"folyta[st]+(a|[ao]?[dn]|ni|[aá]s)?","wordclass":"regex","exc":[{"stem":"((m[eé]g)?[ns]em*i?|baj)","wordclass":"regex"}]},{"stem":"következő","affix":["t","re"]}],
		"back"				: [{"stem":"back"},{"stem":"vissza","max_words":5,"affix":["lép","lépés"],"exc":[{"stem":"hang\w*","wordclass":"regex"}]},{"stem":"hátra","max_words":4},{"stem":"előző","wordclass":"noun","max_words":5}],
		"save"				: [{"stem":"save"},{"stem":"ment","wordclass":"verb"},{"stem":"mentés","wordclass":"noun"}],
		"open"				: [{"stem":"open","exc":[{"stem":"menü","wordclass":"noun"}]},{"stem":"nyit","wordclass":"verb","exc":[{"stem":"menü","wordclass":"noun"}]},{"stem":"nyis","match_stem":False,"wordclass":"verb","exc":[{"stem":"menü","wordclass":"noun"}]}],
		"delete"				: [{"stem":"del","affix":["ete"]},{"stem":"töröl","wordclass":"verb"},{"stem":"törlés"},{"stem":"(kuk[aá]|lomt[aá]r)(ba)?","wordclass":"regex"}],
		"exit"					: [{"stem":"(exit|quit)(elj([eé][dln])?)?","wordclass":"regex"},{"stem":"esc","affix":["ape"]},{"stem":"kilép","wordclass":"verb","prefix":[],"affix":["ás"]},{"stem":"bezár","wordclass":"verb","prefix":[],"affix":["ás"]},{"stem":"(l[eé]pj?([eé][dln])?.+?ki|z[aá]r(ja)?d?.+?be)","wordclass":"regex"},{"stem":"(kapcso[lj]\w{1,3}\s?(m[aá]r\s)?(ki|le))|(csuk\w{1,3}\s?(m[aá]r\s)?be)","wordclass":"regex"}],
		"options"			: [{"stem":"options","wordclass":"noun"},{"stem":"settings","wordclass":"noun"},{"stem":"be[aá]l+[ií]t\w*","wordclass":"regex"},{"stem":"[aá]l+[ií]ts.+?be","wordclass":"regex"}],
		"menu"				: [{"stem":"menü","prefix":["main","fő","al","legördülő"],"affix":["pont","elem"],"wordclass":"noun"}],
		"login"				: [{"stem":"login"},{"stem":"log in"},{"stem":"belép","prefix":[],"wordclass":"verb"},{"stem":"bejelentkez","prefix":[],"wordclass":"verb"},{"stem":"l[eé]p.+?\sbe","wordclass":"regex"},{"stem":"jelentkez.+?\sbe","wordclass":"regex"}],
		"logout"				: [{"stem":"logout"},{"stem":"log out"},{"stem":"kilép","prefix":[],"wordclass":"verb"},{"stem":"kijelentkez","prefix":[],"wordclass":"verb"},{"stem":"l[eé]p.+?\ski","wordclass":"regex"},{"stem":"jelentkez.+?\ski","wordclass":"regex"}],
		"error"				: [{"stem":"error","wordclass":"noun"},{"stem":"hiba","wordclass":"noun"},{"stem":"rossz","wordclass":"adjective","exc":[{"stem":"[eé]rzem|kedv(e[dm]?)?|vagyok","wordclass":"regex"}]},{"stem":"nem\s?(siker[uü]lt|j[oó]l?|m[uüű]k[oö]d(ik|[oö]t+)|ment)(\s\w)?(\s\w)?$","wordclass":"regex"},{"stem":"(le|ki|be|meg)fagyot+","wordclass":"regex"},{"stem":"nem megy"}],
		"search"				: [{"stem":"keres","wordclass":"verb"},{"stem":"find"},{"stem":"találd meg"}],
		"undo"				: [{"stem":"visszavon","wordclass":"verb","prefix":[]},{"stem":"vis+za(.+?eg[eé]szet|l[eé]p([eé]s)?)","wordclass":"regex"},{"stem":"von.+?vis+za","wordclass":"regex","exc":[{"stem":"mégse"}]},{"stem":"undo"}],
		"redo"				: [{"stem":"mégis"},{"stem":"(meg)ism[eé]t(l[eé]s|el(je)?d?)?","wordclass":"regex"},{"stem":"el[oöő]rel[eé]p([eé]s)?","wordclass":"regex"},{"stem":"l[eé]p.+?el[oöő]re","wordclass":"regex"},{"stem":"redo"},{"stem":"m[eé]gse.+?von.+?vis+za","wordclass":"regex"}],
		"restart"			: [{"stem":"ind[ií][ct]+sa?d?(\sel)?(\s[uú]j(ra|b[oó]l))","wordclass":"regex"},{"stem":"újraindít","wordclass":"verb"},{"stem":"(([uú]jra)?kezd\w{0,5}|kezd\w{0,5}.+?([uú]jra|el[oöő]l?r[oö]l|(leg)?elej[eé](t|r)[oöő]l))","wordclass":"regex"}],
		"play"				: [{"stem":"(le)?j[aá](ts+z|c+)([aá]([dls]|ni))?(\sle)?(\svalamit?)?(\segy)?","wordclass":"regex"},{"stem":"play"},{"stem":"indít","wordclass":"verb","prefix":["el"],"exc":[{"stem":"újra"}]}],
		"stop"				: [{"stem":"(meg|le)?[aá]l+(j+([aá]l)?|[ií][ct]+(s?a?d|sa|[aá](ni|s)))(\smeg|\sle)?","wordclass":"regex"},{"stem":"stop"},{"stem":"el[eé]g(\sis)?(\sle(sz|gyen))?(\sm[aá]r)?(\smost)?(\sen+yi)?","wordclass":"regex"},{"stem":"(kus+(olj([aá]l)?)?|fog(ja)?d\s?be)","wordclass":"regex"},{"stem":"(s+h{2,})|(p+s+z*t+)","wordclass":"regex"}],
		"pause"				: [{"stem":"pau[sz][aáeé]([lz]+((as+a|[jz]a)?[dj]|[jz]a|ni))?(\sle)?","wordclass":"regex"},{"stem":"sz[uü]net(elt?(et)?([eé]?s+e?d?|ni)?)?","wordclass":"regex"}],
		"resume"			: [{"stem":"folyta\w+","wordclass":"regex"},{"stem":"resume"}],
		"skip"				: [{"stem":"(kihagy\w+|hag+yj?a?d?\ski|([aá]t|tov[aá]b+)(l[eé]p|ugr[aá])\w*|(ugr[aá]s|ugor\w+|l[eé]p(je)?[dn])\s([aá]t|tov[aá]b+))","wordclass":"regex"},{"stem":"(sz?kip+(el\w*)?|m[aá]sikat)","wordclass":"regex"}],
		"snooze"			: [{"stem":"(sz[uú]ndi\w*|sz[uü]net\w*|sn[ouú]+z[eo]\w*|m[eé]g\s\d\sperc\w*|(sz[oó]lj\w*(\sr[aá]m)|jelez+[eé]?[dl]|cs[eoö]nges\w*)\s([uú]jra\s)?((kicsivel\s)?k[eé]s[oöő]b+)|\d\sperc\w*)","wordclass":"regex"}],
		"volume_up"		: [{"stem":"((n[oö]vel\w+|magas\w+|fel|t[oö]b+)\s(\w+\s)?hang(er)?[oöő]?t?|hang(er)?[oöő]?t?\s(n[oö]vel\w+|magas\w+|fel))","wordclass":"regex"},{"stem":"hangos\w+","wordclass":"regex","exc":[{"stem":"túl"}]},{"stem":"t[uú]l\shalk\w*","wordclass":"regex","exc":[{"stem":"túl"}]},{"stem":"(nem|alig|sem+it\s[ns]em?)\shal+[ao][km]","wordclass":"regex"},{"stem":"adj\w*(\sm[eé]g)?(\sr[aá])?(\sm[eé]g)?\s(hang\w+t|kaka[oó]t)","wordclass":"regex"}],
		"volume_down"	: [{"stem":"((cs[oö]k+en\w+|alacsony\w+|le(j+eb+)?|keveseb+)\s(\w+\s)?hang(er)?[eoöő]?(j[aáeé])?t?|hang(er)?[eoöő]?(j[aáeé])?t?\s(cs[oö]k+en\w+|alacsony\w+|le(j+eb+)?))","wordclass":"regex"},{"stem":"t[uú]l\shangos\w*","wordclass":"regex"},{"stem":"halk[aií]\w+","wordclass":"regex","exc":[{"stem":"túl"}]}],
		"mute"				: [{"stem":"n[eé]m[aáií]\w{0,3}","wordclass":"regex","exc":[{"stem":"vége"},{"stem":"vissza"},{"stem":"feloldás","affix":["a"]}]},{"stem":"mute","wordclass":"verb","prefix":["le","ki"]},{"stem":"(kus+(ol\w*)?|cs[eoö]nd(ben?|et)?)(\sel|\s?legyen)?","wordclass":"regex"}],
		"unmute"			: [{"stem":"n[eé]m[aáií]\w{0,3}","wordclass":"regex","inc":[{"stem":"vége"},{"stem":"vissza"},{"stem":"feloldás","affix":["a"]}]},{"stem":"unmute","wordclass":"verb","prefix":[]},{"stem":"hang(o\w+)?","wordclass":"regex","inc":[{"stem":"vissza"}]}]
	}
	
# hungarian counties and county seats
def counties():
	return {
		"bacs-kiskun"		: [{"stem":"Bács-Kiskun","wordclass":"noun"},{"stem":"Kecskemét","wordclass":"noun"}],
		"baranya"			: [{"stem":"Baranya","wordclass":"noun"},{"stem":"Pécs","affix":["ett"],"wordclass":"noun"}],
		"bekes"				: [{"stem":"Békés","wordclass":"noun"},{"stem":"Békéscsaba","wordclass":"noun"}],
		"borsod-abauj-zemplen": [{"stem":"Borsod","affix":["-Abaúj-Zemplén"],"wordclass":"noun"},{"stem":"Zemplén","wordclass":"noun"},{"stem":"BAZ","ignorecase":False}],
		"csongrad"			: [{"stem":"Csongrád","wordclass":"noun"},{"stem":"Szeged","wordclass":"noun"}],
		"fejer"				: [{"stem":"Fejér","wordclass":"noun"},{"stem":"Fehérvár","prefix":["Székes"],"wordclass":"noun"}],
		"gyor-moson-sopron"	: [{"stem":"Győr","affix":["-Moson-Sopron"],"wordclass":"noun"},{"stem":"Sopron","wordclass":"noun"}],
		"hajdu-bihar"		: [{"stem":"Hajdú-Bihar","wordclass":"noun"},{"stem":"Debrecen","wordclass":"noun"}],
		"heves"				: [{"stem":"Heves","wordclass":"noun"},{"stem":"Eger","wordclass":"noun"},{"stem":"egri"}],
		"jasz-nagykun-szolnok": [{"stem":"Szolnok","wordclass":"noun","prefix":["Jász-Nagykun-"]}],
		"komarom-esztergom"	: [{"stem":"Esztergom","wordclass":"noun","prefix":["Komárom-"]},{"stem":"Komárom","wordclass":"noun"},{"stem":"Tata","affix":["bánya"],"wordclass":"noun"}],
		"nograd"			: [{"stem":"Nógrád","wordclass":"noun"},{"stem":"Salgótarján","wordclass":"noun"}],
		"pest"				: [{"stem":"Buda","wordclass":"noun","affix":["pest"]},{"stem":"Pest","wordclass":"noun"},{"stem":"[IVX]+.?(-?ik)?\sker([uü]let)?\w{0,3}","wordclass":"regex"}],
		"somogy"			: [{"stem":"Somogy","wordclass":"noun"},{"stem":"Kaposvár","wordclass":"noun"}],
		"szabolcs-szatmar-bereg": [{"stem":"Szabolcs","wordclass":"noun","affix":["-Szatmár-Bereg"]},{"stem":"Szatmár","wordclass":"noun"},{"stem":"Nyíregyháza","wordclass":"noun"}],
		"somogy"			: [{"stem":"Somogy","wordclass":"noun"},{"stem":"Kaposvár","wordclass":"noun"}],
		"tolna"				: [{"stem":"Tolna","wordclass":"noun"},{"stem":"Szekszárd","wordclass":"noun"}],
		"vas"					: [{"stem":"Vas","wordclass":"noun"},{"stem":"Szombathely","wordclass":"noun"}],
		"veszprem"		: [{"stem":"Veszprém","wordclass":"noun"}],
		"zala"				: [{"stem":"Zala","wordclass":"noun","affix":["egerszeg"]}]
	}

# days of the week
def dow():
	return {
		"ma"					: [{"stem":"m[aá](ig?|ra|val|t[oó]l)?","wordclass":"regex"}],
		"holnap"			: [{"stem":"holnap(ig?|ra|pal|t[oó]l)?","wordclass":"regex","exc": [{"stem":"holnap\s?ut[aá]n(ig?|ra|nal|t[oó]l)?","wordclass":"regex"}]}],
		"holnaputan"		: [{"stem":"holnap\s?ut[aá]n(ig?|ra|nal|t[oó]l)?","wordclass":"regex"}],
		"tegnap"			: [{"stem":"tegnap(ig?|ra|pal|t[oó]l)?","wordclass":"regex","exc":[{"stem":"tegnap\sel[oő]t+?(ig?|re|t?el|t?[oó]l)?","wordclass":"regex"}]}],
		"tegnapelott"		: [{"stem":"tegnap\sel[oő]t+(ig?|re|t?el|t?[oó]l)?","wordclass":"regex"}],
		"hetfo"				: [{"stem":"hétfő","wordclass":"noun"}],
		"kedd"				: [{"stem":"kedd","wordclass":"noun"}],
		"szerda"				: [{"stem":"szerda","wordclass":"noun"}],
		"csutortok"			: [{"stem":"csütörtök","wordclass":"noun"}],
		"pentek"			: [{"stem":"péntek","wordclass":"noun"}],
		"szombat"			: [{"stem":"szombat","wordclass":"noun"},{"stem":"szonbat","wordclass":"noun"}],
		"vasarnap"			: [{"stem":"vasárnap","wordclass":"noun"}],
		"hetkoznap"		: [{"stem":"hétköznap","wordclass":"noun"},{"stem":"hétfő","wordclass":"noun"},{"stem":"kedd","wordclass":"noun"},{"stem":"szerda","wordclass":"noun"},{"stem":"csütörtök","wordclass":"noun"},{"stem":"péntek","wordclass":"noun"}],		
		"hetvege"			: [{"stem":"hétvége","wordclass":"noun"},{"stem":"szombat","wordclass":"noun"},{"stem":"szonbat","wordclass":"noun"},{"stem":"vasárnap","wordclass":"noun"}]
	}

# small talk intents
def smalltalk():
	return {
		"user_love"		: [{"stem":"szeretlek","exc":[{"stem":"nem"}]},{"stem":"szeretsz engem","exc":[{"stem":"nem"}]},{"stem":"tetszek neked","exc":[{"stem":"nem"}]},{"stem":"tetszel nekem","exc":[{"stem":"nem"}]},{"stem":"szerelmes.+?bel[eé]d","wordclass":"regex","exc":[{"stem":"nem"}]},{"stem":"bel[eé]d.+?(szeret|es)tem","wordclass":"regex"},{"stem":"tal([aá]lko|i)z+(hat)?(unk|n[aá]nk)","wordclass":"regex"},{"stem":"([oö]le|karo)[lj]j([aáeé]l)?\s([aá]t|meg|bel[eé]m)","wordclass":"regex"},{"stem":"(meg|[aá]t|bel[eé]m)?([oö]lel|karol)(h[ae]t)?(sz|n[aáeé]l|j)","wordclass":"regex"},{"stem":"(meg)?(cs[oó]kol|puszil)(j([aá]l)?\smeg|sz|hat(sz|n[aá]l)|[oó]z+(hat)?(unk|n[aáeé]n?k))","wordclass":"regex"},{"stem":"(ad|dob|k[uü]ld)([jn]([aáeé]l)?|e?sz)(\segy)?(\snagy)?\s(puszi(k[aá])?t|cs[oó]kot)","wordclass":"regex"},{"stem":"le(szel|n+[eé]l|gy[eé]l)\sa\s(bar[aá]t(om|n[oöő]m)|fi[uú]m|csajom|szerelmem|valent[ií]n\w+)","wordclass":"regex"},{"stem":"ismerkedn","prefix":["meg"],"affix":["i","ék"],"inc":[{"stem":"veled"}]},{"stem":"szeretem","inc":[{"stem":"önt"},{"stem":"magát"}],"exc":[{"stem":"nem"}]}],
		"user_flirting"		: [{"stem":"mi(lyen)?\s(ruha\s)?van\s?(most\s?)?rajtad","wordclass":"regex"},{"stem":"(meg)?(basz|dug)(unk|n[aá]lak|lak)","wordclass":"regex"},{"stem":"sz?exi?(e[lt]\w*)?","wordclass":"regex"},{"stem":"folyt(ogas+([aá]?[dl])?|s([aá]l)?\smeg)\s(a\snyakam(at)?\s)?(a\s|egy\s)?(d[oö]gl[oö]t+|halot+)\smacsk[aá]val","wordclass":"regex"},{"stem":"(le)?szop(sz|ol|(hat)?n[aá]l)","wordclass":"regex"}],
		"user_bored"		: [{"stem":"un(atkoz)?(om|unk)","wordclass":"regex","exc":[{"stem":"nem"}]}],
		"user_happy"		: [{"stem":"j[oó]\s(a\s)?kedvem(\svan)?","wordclass":"regex","exc":[{"stem":"nincs"},{"stem":"nem"}]},{"stem":"jól vagyok","exc":[{"stem":"nincs"},{"stem":"nem"}]},{"stem":"boldog","exc":[{"stem":"(sz[uü]l(i|t[eé]s\w*)|[uü]n+ep\w*|kar[aá]csony\w*|[eé]vfordul\w|([uú]j)?[eé]v\w*|h[uú]sv[eé]t\w*|n[eé]v\s?nap\w*|[ns]em)","wordclass":"regex"}]}],
		"user_sad"			: [{"stem":"j[oó]\s(a\s)?kedvem","wordclass":"regex","inc":[{"stem":"nincs"},{"stem":"nem"}]},{"stem":"szomorú","wordclass":"adjective","inc":[{"stem":"vagyok"}]},{"stem":"nem\s+(vagyok|[eé]rzem).+?j[oó]l","wordclass":"regex"}],
		"user_angry_at_you"	: [{"stem":"ne\s((h[uú]z+|bas+z|d[uü]h[ií])\w*\s?fel|idege(s[ií]ts|lj([eé]l)?\s?(ki)?))","wordclass":"regex"},{"stem":"(ideges|m[eé]rges|d[uü]h[oö]s)\s(vagyok|voltam)","wordclass":"regex"},{"stem":"haragszom","exc":[{"stem":"nem"}]},{"stem":"(mi([eé]r)?t?\s)?nem\s(hal+|[eé]rt)([ae]sz|[eo]d)","wordclass":"regex"},{"stem":"nem?\sbesz[eé]l(j|het(sz)?)\s[ií]gy","wordclass":"regex"},{"stem":"megbántott","affix":["ál"]},{"stem":"ez nem volt szép"}],
		"user_forgiving_you": [{"stem":"meg\s?(van\s)?bocs[aá]l?j?t(o(t+a)?[km]|va)","wordclass":"regex"},{"stem":"(nem|dehogy)\sharagszo[km]","wordclass":"regex"},{"stem":"(sem+i|[ns]i[nc]+s)\s?baj","wordclass":"regex"}],
		"user_sorry"		: [{"stem":"meg\s?(tud(sz|n[aá]l)\s)?bocs[aá]l?j?ta?(ni|sz|od|t*ot+ad)","wordclass":"regex"},{"stem":"ne haragudj"},{"stem":"bocsáss meg","exc":[{"stem":"bocs[aá]s+\s?meg\,?\s?\w+","wordclass":"regex"}]},{"stem":"sajnálom", "exc":[{"stem":"sajn[aá]lom\,?\s?\w+","wordclass":"regex"}]},{"stem":"megbántottalak","inc":[{"stem":"ha"},{"stem":"hogy"}]}],
		"user_friend"		: [{"stem":"(lesz(e[kl]|[uü]nk)|legy[uü]nk|len+[eé][kl]|lehet([uü]nk|n[eé]n?k))\s(az?\s)?(egyik\s|legjob+\s|k[eé]pzele?t(beli)?\s)?([oö]r[oöi]k?[\s\-]?)?(bar[aá]to|bari|havero|spano)[dkm]","wordclass":"regex"},{"stem":"(bar[aá]to[km]|havero[km])\svagy(unk)?","wordclass":"regex"},{"stem":"te\svagy\sa.+?bar[aá]tom","wordclass":"regex"},{"stem":"gyönyörű barátság","affix":["unk"],"inc":[{"stem":"kezdete"}]}],
		"user_back"		: [{"stem":"(vis+za|meg|haza)\s?(is\s)?(j[oö]t+|t?[eé]rt|[eé]rkezt)(em|[uü]nk)","wordclass":"regex"},{"stem":"[io]t+(hon)?\s(is\s)?vagy(ok|unk)","wordclass":"regex"}],
		"how_are_you"	: [{"stem":"hogy vagy"},{"stem":"j[oó](l|b+an)\svagy","wordclass":"regex"},{"stem":"(j[oó]l|hogy)\s[eé]rzed\s(most\s)?magad(at)?","wordclass":"regex"},{"stem":"mizu","affix":["js","jság"]},{"stem":"hogy ityeg"},{"stem":"(hogy\stelt\sa|milyen(\svolt\sa)?)\snapod(\svan)?","wordclass":"regex"},{"stem":"[vw]+h*[aá]+[csz]+[aáu]+p+","wordclass":"regex"},{"stem":"(j[oó]|milyen)\s(a\s)?kedved(\svan)?","wordclass":"regex"},{"stem":"mi\sa(z\s[aá]bra|\sst[aá]jsz)","wordclass":"regex"},{"stem":"hogy\s[eé]rz(i|ed)\smag[aá][dt]","wordclass":"regex"}],
		"about_name"	: [{"stem":"(mond*(ja)?\ski|mi\sa)\s(bece)nev[eé][dt](et)?","wordclass":"regex"},{"stem":"(hogy(an)?|minek)\s(is\s)?(h[ií]v([jn][aá](la)?k|hatom)|nevez+(nek|elek))","wordclass":"regex"},{"stem":"(mi?[eé]rt\s|hogy[\s\-]?hogy\s)(let+\s)?(pont\s)?(ezt?\s(let+\s)?(a\s)?|[ií]gy\s|ilyen\s)(nevez[nt]ek|h[ií]v[nt]ak|neved|nevet\s(kapt[aá][dl]|adt[aá]k))","wordclass":"regex"},{"stem":"mi\sa\s(bece)?neved?","wordclass":"regex","exc":[{"stem":"az|[ae]n+[ae]k|amiben?|amelyik\w*","wordclass":"regex"}]}],
		"about_you"		: [{"stem":"(mes[eé]lj|besz[eé]lj|mondj)([eo]n)?.+?mag(ad|[aá])r[oó]l","wordclass":"regex"},{"stem":"mutatkoz+([aá]l|on)?\s+be","wordclass":"regex"},{"stem":"(be)?muta(koz(hat)?n[aá]l|(tn[aá]d|sd)\s.+?magad(at)?)","wordclass":"regex"},{"stem":"([km]i(\s|\sa\s.+?)vagy te|te [km]i(\s|\sa\s.+?)vagy)","wordclass":"regex"}],
		"about_creator"	: [{"stem":"(ki|hogy(an)?)\s(a\s)?(k[eé]sz([ií]t([oöő]d|et+(ek)?)|[uü]lt([eé]l)?)|gazd[aá]d|programoz([oó]d|ot+|tak)|[ií]rt[aá]k?|(hoz(ot+|tak)|j[oö]t+[eé]l).+?(l[eé]tre|vil[aá]gra|k[oó]dod(at)?)|alkot([oó][dt]+|tak)|teremt(et+|[oöő]d)|(keresztelt|nevezet+|adtak)\sel|adot+\s(neked\s)?nevet)","wordclass":"regex"}],
		"about_look"		: [{"stem":"hogy(an)?\s(n[eé]zn?[eé]l\ski|mutatsz|festesz)","wordclass":"regex"},{"stem":"(k[uü]ldj|mutas+).+?(k[eé]pet|fot[oó]t|sz?elfie?t)\smagadr[oó]l","wordclass":"regex"},{"stem":"(k[uü]ldj|mutas+)\smagadr[oó]l.+?(k[eé]pet|fot[oó]t|sz?elfie?t)","wordclass":"regex"},{"stem":"(van|milyen)\s(az?\s)?(arcod|kin[eé]zeted)","wordclass":"regex"}],
		"about_age"		: [{"stem":"mennyi idős vagy"},{"stem":"hány éves vagy"},{"stem":"melyik évben születtél"},{"stem":"mikor születtél"},{"stem":"(melyik\s[eé]vben|mikor)\sk[eé]sz([uü]lt[eé]l|[ií]tet+ek)","wordclass":"regex"},{"stem":"(h[aá]ny(adik|ban)|mikor\s(van|[uü]n+epled)\s?a?)\ssz[uü]l(et[eé]s|i)napod(at)?","wordclass":"regex"},{"stem":"h[aá]ny\s[eé]vesnek\s.+?\smagad(at)?","wordclass":"regex"},{"stem":"sz[uü]l(et[eé]s)?i?napod(at)?\s(h[aá]nyadik[aá]n|mikor|melyik)","wordclass":"regex"}],
		"about_zodiac"	: [{"stem":"(neked\s)?mi\sa\s(horoszk[oó]pod|csil+agjegyed)","wordclass":"regex"},{"stem":"milyen jegyben születtél"},{"stem":"a\s(te\s)?(horoszk[oó]pod|csil+agjegyed)\smi(csoda)?","wordclass":"regex"},{"stem":"milyen\sjegyben\ssz[uü]let+\w+","wordclass":"regex"}],
		"about_location"	: [{"stem":"(hol|helyen)\s(k[eé]sz[uü]lt[eé]l|k[eé]sz[ií]tet+ek|sz[uü]let+[eé]l|(hoztak|j[oö]t+[eé]l).+?l[eé]tre)","wordclass":"regex"},{"stem":"hon+an\s(sz[aá]rmazol|[ií]rsz|val[oó]\svagy)","wordclass":"regex"},{"stem":"ho(n+an|l)\svagy\s(most\s)?(helyileg|most|pontosan)","wordclass":"regex"},{"stem":"(hol\s|mer+e\s)(laksz|(van|az?).+?ot+honod)","wordclass":"regex"}],
		"about_family"	: [{"stem":"ki(k|t|ket)?\s(az?\s|tartasz\sa\s)?(te\s)?(csal[aá]dod(nak)?|sz[uü]l(t|et+[eé]l)|sz[uü]leid(nek)?|([eé]des)?(any(uk)?[aá]d|ap(uk)?[aá]d)(nak)?)","wordclass":"regex"},{"stem":"csal[aá]dban\s([eé]l(sz|tek)|sz[uü]let+[eé]l)","wordclass":"regex"},{"stem":"(h[aá]ny|van(nak)?)\stestv[eé]rei?d","wordclass":"regex"},{"stem":"(kik?|van(n?ak)?[\-\s]?e?)(\sa)?(\shoz+[aá]d?\s?tartoz[oó]i?d|csal[aá]dod)","wordclass":"regex"}],
		"about_software": [{"stem":"(hogy(hogy|an)?|mit[oöő]l).+?(m[uüű]k[oö]dsz|(tudsz |vagy k[eé]pes )?(meg)?[eé]rte(sz|d|ni)\,? (meg )?(hogy )?(a?mit mond(ok|tam)|a?mit [ií]r(ok|tam)|engem))","wordclass":"regex"},{"stem":"mi(jen|lyen|en|\s?f[eé]le|\s?fajta)\sfekete\s?m[aá]gia","wordclass":"regex"},{"stem":"neur[aá]lis\sh[aá]l[oó]\w*","wordclass":"regex","inc":[{"stem":"vagy"},{"stem":"te"},{"stem":"működ","wordclass":"verb"}]}],
		"about_skills"		: [{"stem":"mi(lyen|(ke)?t|k?re)\s(funkci[oó](id?|kat)\s|dolgok(at|ra)\s|tr[uü]k+([oö]k(et|re)|jeid?)\s|parancsok(at|ra)\s)?(tud(sz|n[aá]l)?\s(csin[aá]lni|mutatni)?|ismer(sz)?|(vagy\s|van\s)?(k[eé]pes|(be|meg)?tan[ií]tva)|tan[ií]tot+[aá]k\s(be|neked|meg)?|(k[eé]pes+[eé]gei?d?|tulajdons[aá]g(o|ai)d?)\svan(nak)?)","wordclass":"regex"}],
		"about_thoughts": [{"stem":"mi(n|re)?\s(gondol(kodsz|ko[dz]ol|sz)|agyalsz|t[oö]prenge?sz|j[aá]r\s(az?\s)?(fejed|agyad)(b[ae]n?)?)","wordclass":"regex"}],
		"are_you_a_robot": [{"stem":"(te\s)?(egy\s)?(igazi\s|val[oó](s|di)\s|h[uú]s[\-\s]?v[eé]r\s)?(ember|szem[eé]ly|(an)?droid)\svagy","wordclass":"regex"},{"stem":"(robot|chatbot|ai|mesters[eé]ges\s?intel+igencia|g[eé]p|humanoid|programozva)\svagy","wordclass":"regex"},{"stem":"(ember+el|szem[eé]l+yel|robot+al|program+al|algoritmus+al|g[eé]p+el)\s(besz[eé]l(get)?ek|csevegek|levelezek|konzult[aá]lok)","wordclass":"regex"},{"stem":"(embernek|szem[eé]lynek|robotnak|programnak|algoritmusnak)\s([ií]ro(gato)?[km]|magyar[aá]zo[km]|[uü]zen(get)?ek)","wordclass":"regex"},{"stem":"(embernek|intel+igensnek|szem[eé]lynek|robotnak|g[eé]pnek)\s(hiszed|tartod|gondolod)\smagad(at)?","wordclass":"regex"}],
		"are_you_hungry": [{"stem":"kérsz","inc":[{"stem":"enni"}]},{"stem":"nem vagy éhes"},{"stem":"éhes vagy"},{"stem":"(nem\s)?en+[eé]l?\s(meg\s)?(most\s)?(velem\s)?valamit?","wordclass":"regex"},{"stem":"(nem vagy kaj[aá]s|kaj[aá]s vagy)","wordclass":"regex"}],
		"are_you_thirsty": [{"stem":"kérsz","inc":[{"stem":"inni"}]},{"stem":"nem vagy szomjas"},{"stem":"szomjas vagy"},{"stem":"(nem\s)?i(n+[aá]|szo)l?\s(meg\s)?(most\s)?(velem\s)?valamit?","wordclass":"regex"}],
		"are_you_busy"	: [{"stem":"elfoglalt","inc":[{"stem":"vagy"}]},{"stem":"r[aá]m?\s?[eé]r(n[eé]l|sz)(\smost)?(\segy)?(\skicsit|\skis\s\w+|\svalamen+yi\w*)?","wordclass":"regex"},{"stem":"(van|volna)\s(most\s)?(r[aá]m?\s)?(most\s)?(egy\s)?(kis\s|kev[eé]s\s|valamen+yi\s)?(szabad\s?)?id[oöő]d(\sr[aá]m)?","wordclass":"regex"},{"stem":"sok dolgod van"}],
		"are_you_lying"	: [{"stem":"hazud","wordclass":"verb"},{"stem":"nem mondt[aá][dl]\s((el|meg)\saz\s)?igaz(at|s[aá]got)","wordclass":"regex"}],
		"are_you_serious": [{"stem":"(nem?|csak)\s(vic+el(sz|j)|mond+(od)?|ideges[ií]ts)","wordclass":"regex"},{"stem":"(ne|csak)?\svic+el(sz|j)","wordclass":"regex"},{"stem":"(komolyan|t[eé]nyleg)\s?([uúií]gy\s|azt\s)?((mond|gondol|[ií]r)(ja|od|tad)|hisz(i|ed)|hit+ed?)","wordclass":"regex"},{"stem":"biztos(an)?\s(vagy\s)?(\w+\s)?(ben+e|eb+en|mondod|mondja)","wordclass":"regex"},{"stem":"ezt?\s(most\s)?komoly(an)?","wordclass":"regex"}],
		"can_you_hear_me": [{"stem":"(olvas+a|hal+ja|n[eé]zi|van\sit+)(\sezt)?\s(vala|b[aá]r)ki(\sis)?","wordclass":"regex"},{"stem":"(hal+(asz|od)|l[aá]t(sz|od)|vesze[ld])\s(engem|a?mit\s(mondok|[ií]rok|k[eé]rdezek))","wordclass":"regex"},{"stem":"valaki\s(hal+(ja)?\s|olvas+a|figyeli?(\sar+a)?)\sa?mit\s(ide\s?|it+\s)?([ií]rok|mondok|k[eé]rdezek)","wordclass":"regex"},{"stem":"felfogtad","max_words":3}],
		"can_you_learn"	: [{"stem":"(k[eé]pes(\svagy)?|tud(sz)?)\stanulni","wordclass":"regex"},{"stem":"tanulsz\s(is|[ae].+?b[oóöő]l)","wordclass":"regex"},{"stem":"[dln][aáeéo][km]\s(be|meg)?tan[ií]tani\b","wordclass":"regex","boundary":False}],
		"can_you_understand_me":[{"stem":"(meg)?[eé]rt(e(d|sz|t+ed?)|i)\,?((\shogy)?\sa?mit\s([ií]r|mond)\w+|\smagyarul)","wordclass":"regex"}]
	}

# smiley and emoji references
def emoji():
	return {
		"like"					: [{"stem":"🙌","wordclass":"emoji"},{"stem":"👏","wordclass":"emoji"},{"stem":"💯","wordclass":"emoji"},{"stem":"👌","wordclass":"emoji"},{"stem":"👍","wordclass":"emoji"},{"stem":"\(Y\)","wordclass":"regex","boundary":False}],
		"dislike"				: [{"stem":"💩","wordclass":"emoji"},{"stem":"👎","wordclass":"emoji"},{"stem":"😒","wordclass":"emoji"},{"stem":"🙄","wordclass":"emoji"},{"stem":"🤢","wordclass":"emoji"},{"stem":"☹️","wordclass":"emoji"}],
		"happiness"		: [{"stem":"😉","wordclass":"emoji"},{"stem":"😃","wordclass":"emoji"},{"stem":"😄","wordclass":"emoji"},{"stem":"🙂","wordclass":"emoji"},{"stem":"[\:\;\=8BX]\-*[p\)\]93]+","wordclass":"regex","boundary":False},{"stem":"[\(\[8]+\-*[\:\;\=8X]","wordclass":"regex","boundary":False}],
		"sadness"			: [{"stem":"😭","wordclass":"emoji"},{"stem":"😢","wordclass":"emoji"},{"stem":"[\:\;\=][\'\,]?\-*[\(\[8]+","wordclass":"regex","boundary":False},{"stem":"[\)\]9]+\-*[\'\,]?[\:\;\=]","wordclass":"regex","boundary":False}],
		"laughter"			: [{"stem":"😀","wordclass":"emoji"},{"stem":"😁","wordclass":"emoji"},{"stem":"😆","wordclass":"emoji"},{"stem":"😝","wordclass":"emoji"},{"stem":"😜","wordclass":"emoji"},{"stem":"[\:\;\=8BX]\-*d[asd]*","wordclass":"regex","boundary":False}],
		"love"				: [{"stem":"😘","wordclass":"emoji"},{"stem":"😍","wordclass":"emoji"},{"stem":"😙","wordclass":"emoji"},{"stem":"😻","wordclass":"emoji"},{"stem":"😗","wordclass":"emoji"},{"stem":"💋","wordclass":"emoji"},{"stem":"❤️","wordclass":"emoji"},{"stem":"💕","wordclass":"emoji"},{"stem":"🍆","wordclass":"emoji"},{"stem":"🏩","wordclass":"emoji"},{"stem":"<+3+","wordclass":"regex","boundary":False}],
		"surprise"			: [{"stem":"😯","wordclass":"emoji"},{"stem":"😲","wordclass":"emoji"},{"stem":"😮","wordclass":"emoji"},{"stem":"[\:\;\=]\-*o+","wordclass":"regex","boundary":False},{"stem":"o+\-*[\:\;\=]","wordclass":"regex","boundary":False}],
		"anger"				: [{"stem":"😡","wordclass":"emoji"},{"stem":">+[\:\;\=]\-*[\(\[8]+","wordclass":"regex","boundary":False},{"stem":"[\)\]9]+\-*[\:\;\=]<+","wordclass":"regex","boundary":False}],
		"discomfort"		: [{"stem":"😱","wordclass":"emoji"},{"stem":"🙀","wordclass":"emoji"},{"stem":"😨","wordclass":"emoji"},{"stem":"d+:","wordclass":"regex","boundary":False},{"stem":"😰","wordclass":"emoji"},{"stem":"😩","wordclass":"emoji"},{"stem":"😓","wordclass":"emoji"}],
		"confusion"			: [{"stem":"😐","wordclass":"emoji"},{"stem":"😕","wordclass":"emoji"},{"stem":"[\:\;\=][\'\,]?\-*[\\\/\|]+","wordclass":"regex","boundary":False},{"stem":"[\\\/\|]+\-*[\'\,]?[\:\;\=]","wordclass":"regex","boundary":False}],
		"tiredness"			: [{"stem":"😪","wordclass":"emoji"},{"stem":"💤","wordclass":"emoji"},{"stem":"😫","wordclass":"emoji"},{"stem":"😴","wordclass":"emoji"}],
		"seduction"		: [{"stem":"💦","wordclass":"emoji"},{"stem":"🍆","wordclass":"emoji"},{"stem":"🛏️","inc":[{"stem":"😏","wordclass":"emoji"},{"stem":"😍","wordclass":"emoji"},{"stem":"😜","wordclass":"emoji"},{"stem":"😛","wordclass":"emoji"}]},{"stem":"🍑","wordclass":"emoji","inc":[{"stem":"🔥","wordclass":"emoji"},{"stem":"😏","wordclass":"emoji"},{"stem":"😍","wordclass":"emoji"},{"stem":"😜","wordclass":"emoji"},{"stem":"😛","wordclass":"emoji"}]},{"stem":"🍌","wordclass":"emoji","inc":[{"stem":"🔥","wordclass":"emoji"},{"stem":"😏","wordclass":"emoji"},{"stem":"😍","wordclass":"emoji"},{"stem":"😜","wordclass":"emoji"},{"stem":"😛","wordclass":"emoji"}]},{"stem":"🚀","wordclass":"emoji","inc":[{"stem":"😏","wordclass":"emoji"},{"stem":"😍","wordclass":"emoji"},{"stem":"😜","wordclass":"emoji"},{"stem":"😛","wordclass":"emoji"}]},{"stem":"💮","wordclass":"emoji","inc":[{"stem":"🔥","wordclass":"emoji"},{"stem":"😏","wordclass":"emoji"},{"stem":"😍","wordclass":"emoji"},{"stem":"😜","wordclass":"emoji"},{"stem":"😛","wordclass":"emoji"}]},{"stem":"🌮","wordclass":"emoji","inc":[{"stem":"😏","wordclass":"emoji"},{"stem":"😍","wordclass":"emoji"},{"stem":"😜","wordclass":"emoji"},{"stem":"😛","wordclass":"emoji"}]},{"stem":"🌋","wordclass":"emoji","inc":[{"stem":"😏","wordclass":"emoji"},{"stem":"😍","wordclass":"emoji"},{"stem":"😜","wordclass":"emoji"},{"stem":"😛","wordclass":"emoji"}]},{"stem":"👅","wordclass":"emoji"}]
	}

# entities you want to ignore in search results or disallow in user inputs
def disallow():
	return {
		"obscene"			: [{"stem":"(fel|le|meg|r[aá]|ki|be|oda|[oö]s+ze|bele|hoz+[aá])?bas*z+d?\s?(at)?(hat)?(us|a[dk]?|n?[aá][kl]|[aá]?t[aáo][lkm]?|ot+|ni|n[aá]n?[dlkm]?|va|meg)?","wordclass":"regex","exc":[{"stem":"megye"}]},{"stem":"((l[oó]|agy)?fasz|fas+z+op[oó]|geci\w*|kurv[aá]([eé]let|an+yj?[aá])?|(be)?fos|ribanc|(be)?szar|buzi|k[oö]cs[oö]g|pin[aá]|pics[aá]|p[oö]cs|p[eé]nisz|(kurva)?any[aá]d)([oö]?k)?r?[aáeoö]?(\w{0,2}[aeoöőu][dnklt]*)?(n[ae]k)?\b","wordclass":"regex","boundary":False},{"stem":"((mother)?f\s?u\s?c\s?k|shit(as{2})?|bitch|pus{2}y|cunt|fag(g?[eo]t)?|penis|blowjob|but{2}(plug|head)?|as{2}|arse|homo|gay|dyke|cock|dick(pic)?)(e?s|ing|e?r)?","wordclass":"regex"}],
		"racist"				: [{"stem":"(fek[aá]|nig+(er|a)|n[aá]ci|cig[oó]|cig[aá]n+y|gypsy|dzsip[oó]|zsidr?[ó])[aáeégklnmstv]*","wordclass":"regex","boundary":False}],
		"erotic"				: [{"stem":"(sz?ex|an[aá]l|[bv]agina|[bp][eé][np]isz?|creampie|cum|sperma?|fuck|homo(kos|sexu[aá]l(is)?)?|milf|bisexual|gay|dild[oó]|vibr[aá]tor|fel+atio|blow\s?job|whore|geci|pus{2}y|pics[aá]|pin[aá]|fasz|pis{2}|boner|dick(pic)?|x{3,}|hentai|catgirl|ec+hi|yaoi|loli|shot[aá]|\w*porn[oó]?(film)?)[aáeéioöőuüdgklmnprstvz]*","wordclass":"regex","boundary":False},{"stem":"maki verem"}],
		"unpleasant"		: [{"stem":"AIDS","wordclass":"noun"},{"stem":"HIV","ignorecase":False},{"stem":"Hitler","wordclass":"noun"},{"stem":"(Sz?t[aá]lin|Len+in)\w*","wordclass":"regex"},{"stem":"pedof[ií]l(i[aá])?[aokltv]*","wordclass":"regex"},{"stem":"(fur{2}y|bestiality|yif{2}y?)[aáeégklnmstv]*","wordclass":"regex"}],
	}
	
# decide whether user is talking to you in a formal or informal way
def tone():
	return {
		"formal"				: [{"stem":"\w+?([bcdfghjklmnpstvy]{1,2}|j)[eo]n","wordclass":"regex"},{"stem":"\w+?n[aeé]m?","wordclass":"regex"},{"stem":"ön","wordclass":"noun"},{"stem":"maga","wordclass":"noun"},{"stem":"(k[eé]r(het)n?[eé]m|megk[eé]rni)","wordclass":"regex"}],
		"informal"			: [{"stem":"\w+?([bcdfghjklmnpstvy]{1,2}|j)[aáeé][dl]","wordclass":"regex"},{"stem":"\w+?([ln][aeé][dlk]|[eo][dlk]|sz)","wordclass":"regex"},{"stem":"(t[eé](ged)?|veled|neked|hoz+[aá]d|t[oöő]led|magad(nak|at|dal|hoz|t[oó]l)?)","wordclass":"regex"}]
	}